language: android

# Specify jdk to run lambda expression
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra
  # Ressource(s) to run emulator during test
    - sys-img-armeabi-v7a-android-23

# Build
script:
  - ./gradlew assembleAndroidTest
